import React, { useEffect, useMemo, useState } from 'react';
import { Download, FileText, ImagePlus, Loader2, Trash2, UploadCloud } from 'lucide-react';
import { useHR } from '../../context/HRContext';
import { deleteGeneratedDocumentApi, generateHrDocumentApi, getCompanyLetterheadApi, listGeneratedDocumentsApi, saveCompanyLetterheadApi, type Phase5GeneratedDocument, type Phase5Letterhead } from '../../lib/authApi';

type TemplateKey = 'employee_contract' | 'device_home_taking';
const templates = [
  { key:'employee_contract' as TemplateKey, name:'Employee Contract', letterhead:false, description:'Employment agreement and NDA. Company letterhead is not applied.' },
  { key:'device_home_taking' as TemplateKey, name:'Device Home-Taking Form', letterhead:true, description:'Office equipment home-taking form generated on the active company letterhead.' },
];
const fields: Record<TemplateKey, Array<{key:string; label:string; type?:string; auto?:string}>> = {
 employee_contract:[
  {key:'today_date',label:'Agreement Date (A.D.)'},{key:'company_name',label:'Company Name',auto:'company'},{key:'employee_name',label:'Employee Name',auto:'employee'},{key:'permanent_address',label:'Permanent Address'},{key:'citizenship_details',label:'Citizenship No. / Issue Date / District'},{key:'salary_amount',label:'Monthly Salary (Rs.)'},{key:'salary_words',label:'Salary in Words'},{key:'working_hours',label:'Working Hours (e.g. 8 AM to 4 PM)'},{key:'ceo_name',label:'CEO Name'},{key:'join_date',label:'Join Date (A.D.)'},{key:'basic_percent',label:'Basic Percentage',auto:'60%'},{key:'allowance_percent',label:'Allowance Percentage',auto:'40%'},{key:'total_salary',label:'Total Salary'}],
 device_home_taking:[
  {key:'employee_name',label:'Employee Name',auto:'employee'},{key:'designation',label:'Designation'},{key:'contact_no',label:'Contact Number'},{key:'email',label:'Email Address'},{key:'reason',label:'Reason for Taking Equipment Home'},{key:'device_count',label:'Number of Devices'},{key:'device_name',label:'Device Name(s)'},{key:'imei_processor',label:'IMEI / Processor'},{key:'device_id',label:'Device ID'},{key:'additional_info',label:'Additional Information'},{key:'recent_equipment',label:'Recently Taken Equipment'},{key:'from_date',label:'From Date',type:'date'},{key:'return_date',label:'Returning Date',type:'date'},{key:'duration',label:'Duration'},{key:'approved_by',label:'Approved By (Director/CEO/COO)'}]
};
function downloadBase64(fileName:string, mimeType:string, base64:string){ const a=document.createElement('a'); a.href=`data:${mimeType};base64,${base64}`; a.download=fileName; document.body.appendChild(a); a.click(); a.remove(); }
export const DocumentGeneratorPanel: React.FC = () => {
 const { users, currentUser } = useHR();
 const [templateKey,setTemplateKey]=useState<TemplateKey>('employee_contract');
 const [employeeId,setEmployeeId]=useState(''); const [values,setValues]=useState<Record<string,string>>({});
 const [letterhead,setLetterhead]=useState<Phase5Letterhead|null>(null); const [history,setHistory]=useState<Phase5GeneratedDocument[]>([]);
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const employees=useMemo(()=>users.filter(u=>u.role==='team_member'||u.role==='hr_manager'),[users]);
 const selectedEmployee=employees.find(e=>String(e.id)===employeeId);
 const refresh=async()=>{ const [lh,docs]=await Promise.all([getCompanyLetterheadApi(),listGeneratedDocumentsApi()]); setLetterhead(lh.letterhead); setHistory(docs.documents); };
 useEffect(()=>{void refresh().catch(e=>setMessage(e instanceof Error?e.message:'Unable to load documents.'));},[]);
 useEffect(()=>{ const t=templates.find(x=>x.key===templateKey)!; const next:Record<string,string>={}; fields[templateKey].forEach(f=>{ if(f.auto==='company')next[f.key]=currentUser.companyName||''; else if(f.auto==='employee')next[f.key]=selectedEmployee?.name||''; else if(f.auto)next[f.key]=f.auto; else next[f.key]=''; }); if(selectedEmployee){ next.designation=selectedEmployee.designation||next.designation||''; next.email=selectedEmployee.email||next.email||''; } setValues(next); setMessage(t.letterhead&&!letterhead?'Upload the company letterhead before generating this document.':''); },[templateKey,employeeId,letterhead,currentUser.companyName]);
 const uploadLetterhead=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0]; if(!file)return; if(!['image/png','image/jpeg'].includes(file.type)){setMessage('Use an A4 PNG or JPG letterhead.');return;} if(file.size>4*1024*1024){setMessage('Letterhead must be 4 MB or smaller.');return;} const reader=new FileReader(); reader.onload=async()=>{setBusy(true);try{const res=await saveCompanyLetterheadApi({fileName:file.name,mimeType:file.type,dataUrl:String(reader.result)});setLetterhead(res.letterhead);setMessage('Company letterhead saved.');}catch(err){setMessage(err instanceof Error?err.message:'Upload failed.');}finally{setBusy(false);}};reader.readAsDataURL(file);};
 const generate=async()=>{const meta=templates.find(x=>x.key===templateKey)!; if(meta.letterhead&&!letterhead){setMessage('Please upload the company letterhead first.');return;} setBusy(true);setMessage('');try{const r=await generateHrDocumentApi({templateKey,employeeId:employeeId?Number(employeeId):undefined,fields:values});downloadBase64(r.fileName,r.mimeType,r.base64);await refresh();setMessage('Document generated and downloaded.');}catch(err){setMessage(err instanceof Error?err.message:'Generation failed.');}finally{setBusy(false);}};
 return <div className="phase5-docs space-y-5">
  <div className="glass-card p-5"><div className="flex items-start justify-between gap-4 flex-wrap"><div><h2 className="text-xl font-extrabold text-slate-900">HR Document Generator</h2><p className="text-sm text-slate-500 mt-1">Generate employee contracts and device home-taking forms.</p></div><label className="doc-upload-btn"><UploadCloud className="w-4 h-4"/> {letterhead?'Replace Letterhead':'Upload Letterhead'}<input type="file" accept="image/png,image/jpeg" onChange={uploadLetterhead}/></label></div>{letterhead&&<div className="letterhead-status"><img src={letterhead.dataUrl} alt="Company letterhead preview"/><div><b>Active company letterhead</b><span>{letterhead.fileName}</span></div></div>}</div>
  <div className="grid lg:grid-cols-[280px_1fr] gap-5"><div className="glass-card p-4"><div className="text-xs font-bold uppercase text-slate-500 mb-3">Templates</div>{templates.map(t=><button key={t.key} onClick={()=>setTemplateKey(t.key)} className={`doc-template-button ${templateKey===t.key?'active':''}`}><FileText className="w-5 h-5"/><span><b>{t.name}</b><small>{t.letterhead?'Uses letterhead':'No letterhead'}</small></span></button>)}</div>
   <div className="glass-card p-5"><h3 className="font-extrabold text-slate-900">{templates.find(t=>t.key===templateKey)?.name}</h3><p className="text-sm text-slate-500 mb-5">{templates.find(t=>t.key===templateKey)?.description}</p><div className="grid md:grid-cols-2 gap-4"><label className="doc-field"><span>Employee</span><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Select employee…</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.employeeCode||e.email}</option>)}</select></label>{fields[templateKey].map(f=><label className="doc-field" key={f.key}><span>{f.label}</span><input type={f.type||'text'} value={values[f.key]||''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/></label>)}</div>{message&&<div className="doc-message">{message}</div>}<div className="flex justify-end mt-5"><button className="glass-btn-primary px-5 py-3 rounded-xl text-white font-bold flex items-center gap-2" disabled={busy} onClick={generate}>{busy?<Loader2 className="w-4 h-4 animate-spin"/>:<Download className="w-4 h-4"/>} Generate & Download DOCX</button></div></div></div>
  <div className="glass-card p-5"><h3 className="font-extrabold text-slate-900 mb-4">Generated Documents</h3>{history.length===0?<div className="doc-empty"><ImagePlus className="w-8 h-8"/><p>No generated documents yet.</p></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Document</th><th>Employee</th><th>Generated By</th><th>Date</th><th></th></tr></thead><tbody>{history.map(d=><tr key={d.id}><td>{d.documentName}</td><td>{d.employeeName||'—'}</td><td>{d.generatedByName}</td><td>{new Date(d.generatedAt).toLocaleString()}</td><td><button className="icon-danger" onClick={async()=>{if(!confirm('Delete this generated document record?'))return;await deleteGeneratedDocumentApi(d.id);await refresh();}}><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div>}</div>
 </div>;
};
