import React, { createContext, useContext, useState, useEffect } from 'react';
import {
  UserProfile,
  UserRole,
  Organization,
  AttendanceRecord,
  LeaveRequest,
  TaskItem,
  Notice,
  Asset,
  Contract,
  Invitation,
  SalarySlip,
  AuditLog,
  TaskStatus
} from '../types';
import {
  INITIAL_ORGANIZATIONS,
  INITIAL_USERS,
  INITIAL_ATTENDANCE,
  INITIAL_LEAVES,
  INITIAL_TASKS,
  INITIAL_NOTICES,
  INITIAL_ASSETS,
  INITIAL_CONTRACTS,
  INITIAL_INVITATIONS,
  INITIAL_SALARY_SLIPS,
  INITIAL_AUDIT_LOGS,
  INITIAL_FAQS
} from '../data/mockData';
import { getStoredData, saveStoredData } from '../lib/storage';
import { createInvitation as createInvitationRequest, listUsers as listUsersRequest, setUserStatus as setUserStatusRequest } from '../lib/authApi';

// The one pre-designated Admin account. Everyone else joins strictly via an
// invitation code generated by an Admin/HR Manager/Superadmin — there is no
// "instant role switch" in the real app.
export const ADMIN_EMAIL = 'teampujan@gmail.com';

interface HRContextType {
  // Current user & Auth state
  currentUser: UserProfile;
  activeRole: UserRole;
  loginWithEmail: (email: string, displayNameHint?: string) => UserProfile;
  hydrateSessionFromServer: (authUser: { id: number; email: string; fullName: string; role: UserRole; employeeCode?: string; designation?: string; department?: string }) => UserProfile;
  clearSession: () => void;
  updateCurrentUserProfile: (updated: Partial<UserProfile>) => void;
  
  // App Collections
  users: UserProfile[];
  organizations: Organization[];
  attendanceRecords: AttendanceRecord[];
  leaveRequests: LeaveRequest[];
  tasks: TaskItem[];
  notices: Notice[];
  assets: Asset[];
  contracts: Contract[];
  invitations: Invitation[];
  salarySlips: SalarySlip[];
  auditLogs: AuditLog[];
  faqs: typeof INITIAL_FAQS;

  // Actions
  toggleUserActiveStatus: (userId: string) => void;
  addOrUpdateEmployee: (emp: UserProfile) => void;
  
  // Attendance actions
  checkInCurrentEmployee: (notes?: string) => void;
  checkOutCurrentEmployee: () => void;
  addAttendanceRecord: (record: Omit<AttendanceRecord, 'id'>) => void;

  // Leave actions
  submitLeaveRequest: (req: Omit<LeaveRequest, 'id' | 'status' | 'appliedOn'>) => void;
  reviewLeaveRequest: (leaveId: string, status: 'Approved' | 'Rejected', comment?: string) => void;

  // Task actions
  addTask: (task: Omit<TaskItem, 'id' | 'createdAt'>) => void;
  updateTaskStatus: (taskId: string, newStatus: TaskStatus) => void;
  deleteTask: (taskId: string) => void;

  // Notice actions
  addNotice: (notice: Omit<Notice, 'id' | 'date'>) => void;
  deleteNotice: (noticeId: string) => void;

  // Asset actions
  addAsset: (asset: Omit<Asset, 'id'>) => void;
  updateAssetStatus: (assetId: string, status: Asset['status'], assignedTo?: string, assignedToName?: string) => void;

  // Contract actions
  addContract: (contract: Omit<Contract, 'id'>) => void;

  // Invitation & Auth simulation actions
  createInvitation: (email: string, role: UserRole) => Promise<Invitation>;
  verifyOtpAndCompleteSignup: (
    invitationCodeOrEmail: string,
    otpCode: string,
    password: string,
    details: Partial<UserProfile>
  ) => boolean;

  // Superadmin Organization actions
  addOrganization: (org: Omit<Organization, 'id'>) => void;
  updateOrganizationStatus: (orgId: string, status: Organization['status']) => void;
  updateOrganizationPlan: (orgId: string, plan: Organization['plan']) => void;

  // Audit Log
  logAuditAction: (action: string, details: string) => void;
}

const HRContext = createContext<HRContextType | undefined>(undefined);

export const HRProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Load or fallback data
  const [users, setUsers] = useState<UserProfile[]>(() => getStoredData('users', INITIAL_USERS));
  const [organizations, setOrganizations] = useState<Organization[]>(() => getStoredData('orgs', INITIAL_ORGANIZATIONS));
  const [attendanceRecords, setAttendanceRecords] = useState<AttendanceRecord[]>(() => getStoredData('attendance', INITIAL_ATTENDANCE));
  const [leaveRequests, setLeaveRequests] = useState<LeaveRequest[]>(() => getStoredData('leaves', INITIAL_LEAVES));
  const [tasks, setTasks] = useState<TaskItem[]>(() => getStoredData('tasks', INITIAL_TASKS));
  const [notices, setNotices] = useState<Notice[]>(() => getStoredData('notices', INITIAL_NOTICES));
  const [assets, setAssets] = useState<Asset[]>(() => getStoredData('assets', INITIAL_ASSETS));
  const [contracts, setContracts] = useState<Contract[]>(() => getStoredData('contracts', INITIAL_CONTRACTS));
  const [invitations, setInvitations] = useState<Invitation[]>(() => getStoredData('invitations', INITIAL_INVITATIONS));
  const [salarySlips] = useState<SalarySlip[]>(INITIAL_SALARY_SLIPS);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>(() => getStoredData('audit_logs', INITIAL_AUDIT_LOGS));

  // Current active role & active user profile.
  // No one is "logged in" until loginWithEmail() succeeds — this placeholder
  // is only ever read before that point (i.e. while the LoginPage is showing,
  // which never reads currentUser), and gets overwritten immediately on login.
  const [activeRole, setActiveRole] = useState<UserRole>('team_member');
  const [currentUser, setCurrentUser] = useState<UserProfile>(() => ({
    id: 'unauthenticated',
    email: '',
    name: '',
    role: 'team_member',
    isActive: true,
    createdAt: '',
  }));

  // Persist handlers
  useEffect(() => { saveStoredData('users', users); }, [users]);
  useEffect(() => { saveStoredData('orgs', organizations); }, [organizations]);
  useEffect(() => { saveStoredData('attendance', attendanceRecords); }, [attendanceRecords]);
  useEffect(() => { saveStoredData('leaves', leaveRequests); }, [leaveRequests]);
  useEffect(() => { saveStoredData('tasks', tasks); }, [tasks]);
  useEffect(() => { saveStoredData('notices', notices); }, [notices]);
  useEffect(() => { saveStoredData('assets', assets); }, [assets]);
  useEffect(() => { saveStoredData('contracts', contracts); }, [contracts]);
  useEffect(() => { saveStoredData('invitations', invitations); }, [invitations]);
  useEffect(() => { saveStoredData('audit_logs', auditLogs); }, [auditLogs]);

  // Resolve a real, Firebase-authenticated email address to a NexuxHR profile.
  // - If this email already has a profile (created via a previous invite-based
  //   signup, or is the founding Admin), load it and set the active role.
  // - If the email is the one pre-designated Admin account and has no profile
  //   yet, provision it on the spot (first login only).
  // - Otherwise, throw — this person authenticated with Firebase but has no
  //   NexuxHR account, so they need a real invitation code to sign up first.
  const loginWithEmail = (email: string, displayNameHint?: string): UserProfile => {
    const normalizedEmail = email.trim().toLowerCase();
    const existing = users.find(u => u.email.toLowerCase() === normalizedEmail);

    if (existing) {
      setCurrentUser(existing);
      setActiveRole(existing.role);
      logAuditAction('Login', `${existing.name} logged in`);
      return existing;
    }

    if (normalizedEmail === ADMIN_EMAIL) {
      const adminProfile: UserProfile = {
        id: 'usr-admin-owner',
        email: ADMIN_EMAIL,
        name: displayNameHint || 'Admin',
        role: 'admin',
        isActive: true,
        createdAt: new Date().toISOString().split('T')[0],
      };
      setUsers(prev => [adminProfile, ...prev]);
      setCurrentUser(adminProfile);
      setActiveRole('admin');
      logAuditAction('Admin Provisioned', `${adminProfile.name} set up as the founding Admin account`);
      return adminProfile;
    }

    throw new Error('NO_ACCOUNT');
  };

  // Builds/updates the local profile straight from the real cPanel/MySQL
  // account the backend just authenticated (login, OTP verify, or signup).
  // This works regardless of which browser/device the person is on, unlike
  // loginWithEmail() above which only looks at this browser's local data.
  const hydrateSessionFromServer = (authUser: { id: number; email: string; fullName: string; role: UserRole; employeeCode?: string; designation?: string; department?: string }): UserProfile => {
    const normalizedEmail = authUser.email.trim().toLowerCase();
    const realId = String(authUser.id);
    const existing = users.find(u => u.id === realId || u.email.toLowerCase() === normalizedEmail);
    const profile: UserProfile = existing
      ? { ...existing, id: realId, name: authUser.fullName || existing.name, role: authUser.role, employeeCode: authUser.employeeCode || existing.employeeCode, designation: authUser.designation || existing.designation, department: authUser.department || existing.department }
      : {
          id: realId,
          email: normalizedEmail,
          name: authUser.fullName || 'Team Member',
          role: authUser.role,
          employeeCode: authUser.employeeCode,
          designation: authUser.designation,
          department: authUser.department,
          isActive: true,
          createdAt: new Date().toISOString().split('T')[0],
        };
    setUsers(prev => existing ? prev.map(u => (u.id === realId ? profile : u)) : [profile, ...prev]);
    setCurrentUser(profile);
    setActiveRole(profile.role);
    logAuditAction('Login', `${profile.name} logged in`);
    return profile;
  };

  const clearSession = () => {
    setCurrentUser({
      id: 'unauthenticated',
      email: '',
      name: '',
      role: 'team_member',
      isActive: true,
      createdAt: '',
    });
  };

  const updateCurrentUserProfile = (updated: Partial<UserProfile>) => {
    setUsers(prev => prev.map(u => u.id === currentUser.id ? { ...u, ...updated } : u));
    setCurrentUser(prev => ({ ...prev, ...updated }));
    logAuditAction('Profile Update', `Updated profile information for ${currentUser.name}`);
  };

  const toggleUserActiveStatus = async (userId: string) => {
    const target = users.find(u => u.id === userId);
    if (!target) return;
    const nextActive = !target.isActive;
    try {
      await setUserStatusRequest(Number(userId), nextActive ? 'active' : 'inactive');
      setUsers(prev => prev.map(u => u.id === userId ? { ...u, isActive: nextActive } : u));
      logAuditAction('User Status Toggle', `Toggled user ${target.name} active status to ${nextActive}`);
    } catch (err: any) {
      logAuditAction('User Status Toggle Failed', err.message || `Could not update status for ${target.name}`);
    }
  };

  // Keeps the employee directory in sync with the real cPanel/MySQL users
  // table, so every signed-in device/browser sees the same real employee
  // list instead of each browser's own local mock data.
  useEffect(() => {
    if (currentUser.id === 'unauthenticated') return;
    let cancelled = false;
    (async () => {
      try {
        const { users: serverUsers } = await listUsersRequest();
        if (cancelled) return;
        setUsers(prev => serverUsers.map(su => {
          const existing = prev.find(p => p.id === String(su.id));
          return {
            ...(existing as UserProfile | undefined),
            id: String(su.id),
            email: su.email,
            name: su.fullName,
            role: su.role as UserRole,
            employeeCode: su.employeeCode || existing?.employeeCode,
            designation: su.designation || existing?.designation,
            department: su.department || existing?.department,
            isActive: su.status === 'active',
            createdAt: existing?.createdAt || (su.createdAt ? su.createdAt.substring(0, 10) : new Date().toISOString().split('T')[0]),
          } as UserProfile;
        }));
      } catch {
        // Not logged in yet, or the request failed — keep whatever is already loaded.
      }
    })();
    return () => { cancelled = true; };
  }, [currentUser.id]);

  const addOrUpdateEmployee = (emp: UserProfile) => {
    setUsers(prev => {
      const idx = prev.findIndex(u => u.id === emp.id || u.employeeId === emp.employeeId);
      if (idx >= 0) {
        const next = [...prev];
        next[idx] = { ...next[idx], ...emp };
        return next;
      }
      return [emp, ...prev];
    });
    logAuditAction('Employee Saved', `Added or updated employee profile for ${emp.name} (${emp.employeeId || 'New'})`);
  };

  // Attendance handlers
  const todayStr = new Date().toISOString().split('T')[0];
  const todayMonthStr = todayStr.substring(0, 7);

  const checkInCurrentEmployee = (notes?: string) => {
    const timeNow = new Date().toLocaleTimeString('en-US', { hour12: false });
    const existingIndex = attendanceRecords.findIndex(
      a => a.employeeId === (currentUser.employeeId || currentUser.id) && a.date === todayStr
    );

    if (existingIndex >= 0) {
      const updated = [...attendanceRecords];
      updated[existingIndex] = {
        ...updated[existingIndex],
        checkIn: timeNow,
        status: 'Present',
        notes: notes || updated[existingIndex].notes
      };
      setAttendanceRecords(updated);
    } else {
      const newRecord: AttendanceRecord = {
        id: `att-${Date.now()}`,
        employeeId: currentUser.employeeId || currentUser.id,
        employeeName: currentUser.name,
        date: todayStr,
        month: todayMonthStr,
        checkIn: timeNow,
        status: 'Present',
        workHours: 0.1,
        notes: notes || 'Checked in via NexuxHR Portal'
      };
      setAttendanceRecords([newRecord, ...attendanceRecords]);
    }
    logAuditAction('Check-In', `${currentUser.name} checked in at ${timeNow}`);
  };

  const checkOutCurrentEmployee = () => {
    const timeNow = new Date().toLocaleTimeString('en-US', { hour12: false });
    setAttendanceRecords(prev => prev.map(a => {
      if (a.employeeId === (currentUser.employeeId || currentUser.id) && a.date === todayStr) {
        return {
          ...a,
          checkOut: timeNow,
          workHours: 8.5
        };
      }
      return a;
    }));
    logAuditAction('Check-Out', `${currentUser.name} checked out at ${timeNow}`);
  };

  const addAttendanceRecord = (record: Omit<AttendanceRecord, 'id'>) => {
    const newRecord: AttendanceRecord = {
      ...record,
      id: `att-${Date.now()}`
    };
    setAttendanceRecords([newRecord, ...attendanceRecords]);
    logAuditAction('Manual Attendance', `Added manual attendance for ${record.employeeName} on ${record.date}`);
  };

  // Leave Handlers
  const submitLeaveRequest = (req: Omit<LeaveRequest, 'id' | 'status' | 'appliedOn'>) => {
    const newReq: LeaveRequest = {
      ...req,
      id: `lv-${Date.now()}`,
      status: 'Pending',
      appliedOn: todayStr
    };
    setLeaveRequests([newReq, ...leaveRequests]);
    logAuditAction('Leave Request Submitted', `${req.employeeName} submitted ${req.leaveType} for ${req.days} days`);
  };

  const reviewLeaveRequest = (leaveId: string, status: 'Approved' | 'Rejected', comment?: string) => {
    setLeaveRequests(prev => prev.map(l => {
      if (l.id === leaveId) {
        return {
          ...l,
          status,
          reviewComment: comment,
          reviewedBy: `${currentUser.name} (${currentUser.role === 'admin' ? 'Admin' : 'HR'})`
        };
      }
      return l;
    }));
    logAuditAction('Leave Reviewed', `${currentUser.name} set leave request ${leaveId} to ${status}`);
  };

  // Task Handlers
  const addTask = (task: Omit<TaskItem, 'id' | 'createdAt'>) => {
    const newTask: TaskItem = {
      ...task,
      id: `tsk-${Date.now()}`,
      createdAt: todayStr
    };
    setTasks([newTask, ...tasks]);
    logAuditAction('Task Created', `Created task: ${task.title} assigned to ${task.assignedToName}`);
  };

  const updateTaskStatus = (taskId: string, newStatus: TaskStatus) => {
    setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: newStatus } : t));
    logAuditAction('Task Status Updated', `Task ${taskId} moved to ${newStatus}`);
  };

  const deleteTask = (taskId: string) => {
    setTasks(prev => prev.filter(t => t.id !== taskId));
    logAuditAction('Task Deleted', `Deleted task ${taskId}`);
  };

  // Notice Handlers
  const addNotice = (notice: Omit<Notice, 'id' | 'date'>) => {
    const newNotice: Notice = {
      ...notice,
      id: `nt-${Date.now()}`,
      date: todayStr
    };
    setNotices([newNotice, ...notices]);
    logAuditAction('Notice Posted', `Broadcast notice: ${notice.title}`);
  };

  const deleteNotice = (noticeId: string) => {
    setNotices(prev => prev.filter(n => n.id !== noticeId));
    logAuditAction('Notice Deleted', `Removed notice ${noticeId}`);
  };

  // Asset Handlers
  const addAsset = (asset: Omit<Asset, 'id'>) => {
    const newAsset: Asset = {
      ...asset,
      id: `ast-${Date.now()}`
    };
    setAssets([newAsset, ...assets]);
    logAuditAction('Asset Registered', `Registered asset ${asset.assetCode} - ${asset.name}`);
  };

  const updateAssetStatus = (
    assetId: string,
    status: Asset['status'],
    assignedTo?: string,
    assignedToName?: string
  ) => {
    setAssets(prev => prev.map(a => {
      if (a.id === assetId) {
        return {
          ...a,
          status,
          assignedTo: assignedTo ?? a.assignedTo,
          assignedToName: assignedToName ?? a.assignedToName
        };
      }
      return a;
    }));
    logAuditAction('Asset Status Updated', `Asset ${assetId} set to ${status}`);
  };

  // Contract Handlers
  const addContract = (contract: Omit<Contract, 'id'>) => {
    const newContract: Contract = {
      ...contract,
      id: `cnt-${Date.now()}`
    };
    setContracts([newContract, ...contracts]);
    logAuditAction('Contract Added', `Added contract for ${contract.employeeName}`);
  };

  // Invitations
  const createInvitation = async (email: string, role: UserRole): Promise<Invitation> => {
    const empCodeNum = users.length + 1;
    const generatedEmpId = `EMP-2026-00${empCodeNum}`;

    // Creates the invitation in the real MySQL table and emails the invitee
    // via the cPanel mail server — this is what actually reaches their inbox.
    const result = await createInvitationRequest(email, role);

    const newInv: Invitation = {
      id: `inv-${Date.now()}`,
      email,
      role,
      employeeId: generatedEmpId,
      companyId: currentUser.companyId || 'org-1',
      invitedBy: currentUser.id,
      invitedByName: `${currentUser.name} (${currentUser.role})`,
      status: 'Pending',
      createdAt: todayStr,
      code: result.code
    };

    setInvitations(prev => [newInv, ...prev]);
    logAuditAction('Invitation Created', `Sent ${role} invitation to ${email} [${result.code}] with Auto EmpID ${generatedEmpId}`);
    return newInv;
  };

  const verifyOtpAndCompleteSignup = (
    invitationCodeOrEmail: string,
    otpCode: string,
    password: string,
    details: Partial<UserProfile>
  ): boolean => {
    if (!otpCode || otpCode.length < 4) return false;

    const normalizedEmail = (details.email || '').trim().toLowerCase();
    const isFoundingAdmin = normalizedEmail === ADMIN_EMAIL;

    const matchedInv = invitations.find(
      i => i.code.toLowerCase() === invitationCodeOrEmail.toLowerCase() || i.email.toLowerCase() === invitationCodeOrEmail.toLowerCase()
    );

    // Real invite-only gating: everyone except the founding Admin needs a
    // valid, unused invitation to create an account.
    if (!isFoundingAdmin) {
      if (!matchedInv) return false;
      if (matchedInv.status === 'Accepted') return false;
    }

    const assignedRole: UserRole = isFoundingAdmin ? 'admin' : matchedInv!.role;
    const assignedEmpId = isFoundingAdmin
      ? `EMP-${new Date().getFullYear()}-ADMIN`
      : matchedInv!.employeeId;
    const assignedCompanyId = matchedInv?.companyId;
    const assignedCompany = organizations.find(o => o.id === assignedCompanyId);

    const newProfile: UserProfile = {
      id: `usr-${Date.now()}`,
      email: details.email || (matchedInv ? matchedInv.email : ''),
      name: details.name || 'New Team Member',
      role: assignedRole,
      employeeId: assignedEmpId,
      employeeCode: details.employeeCode || `NX-00${users.length + 1}`,
      designation: details.designation || (isFoundingAdmin ? 'Administrator' : 'Software Engineer'),
      department: details.department || 'Operations',
      companyId: assignedCompanyId,
      companyName: assignedCompany?.name,
      dob: details.dob || '1996-01-01',
      citizenshipPan: details.citizenshipPan || '',
      bankDetails: details.bankDetails || {
        bankName: 'National Bank',
        accountNumber: '1029384756',
        accountHolder: details.name || 'New User'
      },
      emergencyPhone: details.emergencyPhone || '',
      guardianPhone: details.guardianPhone || '',
      photoUrl: details.photoUrl,
      isActive: true,
      createdAt: todayStr,
    };

    setUsers(prev => [newProfile, ...prev]);
    if (matchedInv) {
      setInvitations(prev => prev.map(i => i.id === matchedInv.id ? { ...i, status: 'Accepted' } : i));
    }
    setCurrentUser(newProfile);
    setActiveRole(newProfile.role);
    logAuditAction('Signup Complete', `${newProfile.name} verified OTP and completed account setup as ${newProfile.role}`);
    return true;
  };

  // Superadmin Org handlers
  const addOrganization = (org: Omit<Organization, 'id'>) => {
    const newOrg: Organization = {
      ...org,
      id: `org-${Date.now()}`
    };
    setOrganizations([newOrg, ...organizations]);
    logAuditAction('Organization Created', `Created organization: ${org.name}`);
  };

  const updateOrganizationStatus = (orgId: string, status: Organization['status']) => {
    setOrganizations(prev => prev.map(o => o.id === orgId ? { ...o, status } : o));
    logAuditAction('Organization Status Changed', `Set organization ${orgId} to ${status}`);
  };

  const updateOrganizationPlan = (orgId: string, plan: Organization['plan']) => {
    setOrganizations(prev => prev.map(o => o.id === orgId ? { ...o, plan } : o));
    logAuditAction('Organization Plan Changed', `Upgraded organization ${orgId} to ${plan} Plan`);
  };

  const logAuditAction = (action: string, details: string) => {
    const newLog: AuditLog = {
      id: `log-${Date.now()}`,
      action,
      doneBy: currentUser.id,
      doneByName: currentUser.name,
      role: currentUser.role,
      timestamp: new Date().toLocaleString(),
      details
    };
    setAuditLogs(prev => [newLog, ...prev.slice(0, 49)]); // keep latest 50
  };

  return (
    <HRContext.Provider
      value={{
        currentUser,
        activeRole,
        loginWithEmail,
        hydrateSessionFromServer,
        clearSession,
        updateCurrentUserProfile,
        users,
        organizations,
        attendanceRecords,
        leaveRequests,
        tasks,
        notices,
        assets,
        contracts,
        invitations,
        salarySlips,
        auditLogs,
        faqs: INITIAL_FAQS,
        toggleUserActiveStatus,
        addOrUpdateEmployee,
        checkInCurrentEmployee,
        checkOutCurrentEmployee,
        addAttendanceRecord,
        submitLeaveRequest,
        reviewLeaveRequest,
        addTask,
        updateTaskStatus,
        deleteTask,
        addNotice,
        deleteNotice,
        addAsset,
        updateAssetStatus,
        addContract,
        createInvitation,
        verifyOtpAndCompleteSignup,
        addOrganization,
        updateOrganizationStatus,
        updateOrganizationPlan,
        logAuditAction
      }}
    >
      {children}
    </HRContext.Provider>
  );
};

export const useHR = () => {
  const context = useContext(HRContext);
  if (!context) {
    throw new Error('useHR must be used within an HRProvider');
  }
  return context;
};
