export type UserRole = 'superadmin' | 'admin' | 'hr_manager' | 'team_member';

export interface UserProfile {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  employeeId?: string;
  employeeCode?: string;
  designation?: string;
  department?: string;
  companyId?: string;
  companyName?: string;
  dob?: string;
  citizenshipPan?: string;
  bankDetails?: {
    bankName: string;
    accountNumber: string;
    accountHolder: string;
    ifscCode?: string;
  };
  emergencyPhone?: string;
  guardianPhone?: string;
  photoUrl?: string;
  isActive: boolean;
  createdAt: string;
  documents?: {
    photo?: string;
    academicPhoto?: string;
    citizenshipPhoto?: string;
    panNidPhoto?: string;
    others?: string[];
  };
}

export interface Organization {
  id: string;
  name: string;
  code: string;
  plan: 'Starter' | 'Growth' | 'Enterprise';
  billingCycle: 'Monthly' | 'Annual';
  activeEmployeesCount: number;
  maxEmployees: number;
  status: 'Active' | 'Suspended' | 'Trial';
  renewalDate: string;
  contactEmail: string;
}

export interface AttendanceRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string; // YYYY-MM-DD
  month: string; // YYYY-MM
  checkIn?: string; // HH:mm:ss
  checkOut?: string; // HH:mm:ss
  status: 'Present' | 'Absent' | 'Late' | 'Half Day' | 'On Leave';
  workHours?: number;
  notes?: string;
}

export type LeaveStatus = 'Pending' | 'Approved' | 'Rejected';
export type LeaveType = 'Casual Leave' | 'Sick Leave' | 'Annual Leave' | 'Maternity/Paternity' | 'Unpaid Leave';

export interface LeaveRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  designation: string;
  leaveType: LeaveType;
  startDate: string;
  endDate: string;
  days: number;
  reason: string;
  status: LeaveStatus;
  appliedOn: string;
  reviewedBy?: string;
  reviewComment?: string;
}

export type TaskStatus = 'not_started' | 'due' | 'overdue' | 'need_urgent';

export interface TaskItem {
  id: string;
  title: string;
  notes: string;
  status: TaskStatus;
  assignedTo: string; // employeeId or 'self'
  assignedToName: string;
  assignedBy: string;
  assignedByName: string;
  dueDate: string;
  createdAt: string;
  priority: 'Low' | 'Medium' | 'High' | 'Critical';
}

export interface Notice {
  id: string;
  title: string;
  content: string;
  postedBy: string;
  postedByName: string;
  date: string;
  priority: 'Normal' | 'Important' | 'Urgent';
  targetRole?: UserRole | 'All';
}

export interface Asset {
  id: string;
  assetCode: string;
  name: string;
  category: 'Laptop' | 'Mobile' | 'Monitor' | 'Access Card' | 'Furniture' | 'Peripherals';
  assignedTo?: string; // employeeId
  assignedToName?: string;
  status: 'In Use' | 'Available' | 'Under Maintenance' | 'Decommissioned';
  purchaseDate: string;
  serialNumber?: string;
}

export interface Contract {
  id: string;
  contractCode: string;
  employeeId: string;
  employeeName: string;
  designation: string;
  type: 'Full-Time' | 'Part-Time' | 'Probation' | 'Consultant';
  salaryMonthly: number;
  startDate: string;
  endDate?: string;
  status: 'Active' | 'Pending Renewal' | 'Terminated';
  documentUrl?: string;
}

export interface Invitation {
  id: string;
  email: string;
  role: UserRole;
  employeeId: string; // Autogenerated by Admin
  companyId: string;
  invitedBy: string;
  invitedByName: string;
  status: 'Pending' | 'Accepted' | 'Expired';
  createdAt: string;
  code: string; // e.g. "INV-98214"
}

export interface SalarySlip {
  id: string;
  employeeId: string;
  employeeName: string;
  month: string; // e.g. "July 2026"
  basicSalary: number;
  allowances: number;
  deductions: number;
  netPay: number;
  issuedDate: string;
  status: 'Paid' | 'Processing';
}

export interface AuditLog {
  id: string;
  action: string;
  doneBy: string;
  doneByName: string;
  role: UserRole;
  timestamp: string;
  details: string;
}

export interface FAQItem {
  id: string;
  question: string;
  answer: string;
  category: string;
}
